### ISSUE TITLE
Is this project based on the "Set Transformer" architecture?

### ISSUE THREAD

**Issue by VRichardJP** [RyanSaxe/mtg#10]
First, thank you for sharing your experimentations and results. I am thinking about making a similar project, and I have a few questions regarding your approach and implementation:

- From a quick glance, it looks like this project is based on the attention architecture proposed in ["Attention Is All You Need"](https://arxiv.org/abs/1706.03762) paper. More recently, a variant of this archicture for building models with set input was proposed in ["Set Transformer: A Framework for Attention-based Permutation-Invariant Neural Networks"](https://arxiv.org/abs/1810.00825). Have you checked this paper? 
- In your code, you build a block called "MLP". What does this acronym stands for?

**Comment by RyanSaxe** [comment]
Hi @VRichardJP 

1. Yes, I have read that paper, although it isn't recent. I wouldn't recommend a permutation-invariant approach here because draft is fundamentally not permutation invariant as your picks are an ordered sequence.
2. MLP stands for Multi-Layer-Perceptron.

In the future, if you would like to ask me questions about your project or this repository, feel free to DM me on Twitter or Discord rather than opening up a Github Issue.
